services:
  cowrie:
    build:
      context: ../src
      dockerfile: docker/Dockerfile
    container_name: cowrie-honeypot
    restart: unless-stopped
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - ./cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg:ro
      - ./userdb.txt:/cowrie/cowrie-git/etc/userdb.txt:ro
      - cowrie-log:/cowrie/cowrie-git/var/log/cowrie
      - cowrie-tty:/cowrie/cowrie-git/var/lib/cowrie/tty
      - cowrie-downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads
    environment:
      - TZ=Europe/Rome
    networks:
      - honeypot-net

volumes:
  cowrie-log:
  cowrie-tty:
  cowrie-downloads:


networks:
  honeypot-net:
    driver: bridge
